### ISSUE TITLE
I can type a box like that not in R

### ISSUE THREAD

**Issue by jocelyn-cuthbert** [pearselab/r-intro-jocelyn-cuthbert#5]
Tried Box, Rectangle, and now symbol to get the starts (got an impressive 12 errors on that one)
Is one these the right one to use for the function or am I completely off in left field?  I got box to draw me some pretty dashes around the plot....

On a related note, I can only get a single point for the biologist.  It turns purple, red and blue but it isn't a function - do I just insert the original function into the function for plotting?  None of my mostly scientific assumptions about bunnies are showing up!

**Comment by jocelyn-cuthbert** [comment]
Thanks for the help with the plotting - I just saw the email.  I had thought I fixed it and prematurely closed it.  It turns out I definitely didn't fix it.   I think what you told me makes sense - I will try to see if I can make it work in the function!

**Comment by willpearse** [comment]
Are you still having trouble with this question? Which question is it you're trying?

**Comment by jocelyn-cuthbert** [comment]
Yes!  I now have plotting a line - I think the issue was that I never made any of the variables a vector, or gave the function a loop, so that it was always plotting a single dot and not repeating back through.   But I still can't seem to get the box to work through any three of those functions.

**Comment by willpearse** [comment]
Which question are you trying? Could you be more specific? I'm afraid I'm not quite sure what you're talking about :-(

**Comment by jocelyn-cuthbert** [comment]
Sorry!  I am trying question Section 2 #9 (/2.10/2.11) where you are supposed to use a function to draw this box.   I tried functions called Box, rectangle, and symbol and wasn't able to do anything except draw boxes around plots, without specific dimensions.  Is there something I am missing on these functions, or am I completely on the wrong track with those three functions and should be trying something else?

---
-    *
  *****

**Comment by willpearse** [comment]
Right, now I see what you're trying to do. Take a look at the code below, which should give you an idea of how to get started

```
#Top of box
#For loop
    cat("*")
#End loop
cat("\n") #What does this line do?...

#Middle of box
cat("*")
#...figure out a way to space out your text...

#Write out the bottom of the box
```
