### ISSUE TITLE
Advice about new styles of programming

### ISSUE THREAD

**Issue by willpearse** [pearselab/r-intro-jocelyn-cuthbert#6]
I remember in class we talked briefly about how you had learnt to program in another language before. You might remember that I could tell from the way you were using _flags_ in your code. It was easy for me to recognise because I used to be one of those programmers too!

Maybe if I'm more specific about how to avoid using flags, it'll help you. _Please remember that I'm not telling you this because you've done something wrong - quite the opposite_. Your code is very good already, and I'm trying to help you get better. 
- [You set a flag (0) and then don't ever check for that flag.](https://github.com/pearselab/r-intro-jocelyn-cuthbert/blob/9f8c96cdc2a40c0fceff3f6956254704953b389c/Session%202.R#L59) Indeed, you `break` straight afterwards, and you set it to the value that you set it to at the start of the loop. So don't worry about this flag!
- [In another place, you set a flag with the intentional of checking for it later](https://github.com/pearselab/r-intro-jocelyn-cuthbert/blob/9f8c96cdc2a40c0fceff3f6956254704953b389c/Session%202.R#L65). Don't do this - do whatever you were going to do _right now_. That way you avoid the flag, saving memory, time, and making your code shorter

Does that make some sense? I have a lot of sympathy with you because I was taught to use flags too - I promise you, you can get out of the habit :D

**Comment by willpearse** [comment]
Oh yes, and one more thing: try to avoid using `=` - instead, use `<-`. It's less likely to be confused with `==`, and is less flexible for other programmers. If you want me to go through the reasons I can in class, but trust me - you'll have a much better time of it if you only use `=` when you're giving default values for arguments (like in my other comment).

**Comment by jocelyn-cuthbert** [comment]
Hi Will,
So I actually haven't learned any other codes before - I just was working with the girl that had on this problem.  So if the flag is unnecessary, which is telling it once the number hits 1 to stop the -1 (because prime numbers is the n/n-1 continuing on until you hit 1)- how do I tell is to break at that point?  Instead of flag == 1 would it be if i ==1 then break?

**Comment by willpearse** [comment]
Ah, sorry. It's quite difficult to see over the webcam, so I'm having a trouble keeping track of people except for through their usernames!

You're _exactly right_. If you want to `break`, then just `break`! There's no need to record that you want to do so, then later check to see if you wanted to do it.
