### ISSUE TITLE
How to draw numbers from different means in R

### ISSUE THREAD

**Issue by willpearse** [pearselab/r-intro-jocelyn-cuthbert#7]
```{R}
replicate(10, rnorm(10, rnorm(1)))
```

**Comment by willpearse** [comment]
https://appear.in/usubioprogramming

**Comment by willpearse** [comment]
Are you having trouble with the link?

**Comment by jocelyn-cuthbert** [comment]
Sorry!  I was on safari and then my chrome crashed - I am on it now

**Comment by willpearse** [comment]
It's OK. Let me know if you can't get it working and maybe we can Skype?

**Comment by jocelyn-cuthbert** [comment]
I think it is working - I am on the USU programming thing, I just am not sure how to connect to anyone else.  Right now it says 1 person under the group info

**Comment by willpearse** [comment]
https://appear.in/usubioprogramming

join this one, because I'm here and you're not :-(
